version: "3.7"

services:
  containernet:
    build: .
    image: containernet
    container_name: containernet
    hostname: containernet
    stdin_open: true
    tty: true
    privileged: true
    pid: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $SERVER_LOGS:/logs
    environment:
      - SERVER=$SERVER
      - SERVER_PARAMS=$SERVER_PARAMS
      - CLIENT=$CLIENT
      - CLIENT_PARAMS=$CLIENT_PARAMS
      - SCENARIO=$SCENARIO
      - CL_COMMIT=$CL_COMMIT
      - SV_COMMIT=$SV_COMMIT
      - SERVER_LOGS=$SERVER_LOGS
      - CLIENT_LOGS=$CLIENT_LOGS